** 大调小调
在自然大调与和声小调的各个音级上，都可以构成一个它所属调式的自然音三和弦。自然大调的I、IV、V级是大三和弦，II、III、VI级是小三和弦，VII级是减三和弦。
和声小调的I、IV级是小三和弦，V、VI级是大三和弦，III级是增三和弦，II、VII级是减三和弦。

** 和弦色彩
流行音乐中一般只讲大调的和弦而很少把小调单独作为一种调式重新定义和弦，因为流行音乐中关系大小调和弦共用的现象十分普遍，如果用经典和声学解释会颠来倒去搞不清。
下面以用C大调来举例。基本和弦共7个:C,Dm,Em,F,G,Am,Bdim.分别是1，2，3，4，5，6，7级和弦。1，4，5称正三和弦，2，3，6称副三和弦。7级和弦在流行音乐中极为少用。1级和弦也称主和弦，4级和弦也下属和弦，5级和弦也称属和弦。接下来是每个和弦的属性，很重要哦！

1. C，即1级和弦，是用来明确调性的。一般大调的歌曲都以它开始，也以它结束。不过在曲子的中间可以尽量少用主和弦，否则老是给人以终止感，乐曲的进行也会很硬。
2. Dm,即2级和弦，是一个很柔和的和弦，它的最重要用途就是放在属和弦即5级和弦之前。而5级和弦则自然要回到1级和弦，所以很容易就形成了2-5-1的进行。这是一个极其常用的进行。
3. Em,即3级和弦，也是一个十分柔和的和弦。音乐的进行中有了她马上就会变得柔美而略带忧伤。1-3-4的进行，也即在C大调中的C-Em-F是一个很常用的进行。乐曲中本来用1级和弦的地方有时可以考虑换成3级和弦，音乐立即就不强硬了。港台音乐中这种手法很常用。
4. F,即4级和弦，大调中的又一正三和弦，属于骨干和弦之一。它十分明亮，让人感觉心胸开阔，有一种一下子“飞”起来的感觉。我们听到的美国乡村音乐和描写西部大草原和大峡谷的歌曲都使用4级和弦来表现。1级和弦后面跟4级与跟3级和弦是绝对不同的。
5. G,即5级和弦，大调中的第三个正三和弦，任何一首歌曲都不可缺少。它起着对主和弦支撑的作用。乐曲的终止感就是由5-1这样的进行产生的。当然现代流行音乐特别是欧美音乐中不使用5-1终止的歌曲也很多，这正是流行音乐的特色，但5级和弦作为音乐的骨架和弦仍然不可动摇。
6. Am,即6级和弦，一个中性的和弦，如果把它作为主和弦那就是小调了。歌曲肯定会变得忧郁，悲伤。如果6级和弦出现在大调中的某些部分，那它起到的就是连接不同和弦的作用。6级和弦象一座桥，它前面可以接几乎所有的和弦，后面也是如此。它可以是和弦的进行连贯，不呆板。1-6-4-5是极为常用的进行，事实上就用这四个和弦就可以写歌了。
7. Bdim,即7级和弦，在流行音乐中很少用。因为它是减三和弦，有一种向里收缩的紧张感，一般只在某些特定进行中使用，或是为了根音的流动而使用。（这个和弦比较少用，听起来不是很和谐，常用属7和弦代替（属7就是第5级和弦的7和弦））


** 7和弦
大七和弦：以大三和弦为基础，根音与七音相距为大七度的和弦。如Cmaj7,Fmaj7

大小七和弦：以大三和弦为基础，根音与七音相距为小七度的和弦。如G7

小七和弦：以 小三和弦 为基础，根音与七音相距为 小七度 的和弦。如Dm7，Em7、Am7

** 挂留和弦
还有挂留和弦，挂留和弦包括挂二和弦sus2、挂四和弦sus4。比如C（1 3 5），它的挂二和弦就是用二度音代替原来的三度音（1-3，变成1-2），Csus2(1 2 5)。挂四和弦Csus4(1 4 5),用纯四度音代替原来的大三度（1-3变成1-4）。

** 一般旋律

*** 1645

*** 15634345

*** 17654325

*** 6326或者6236

*** Am—F—C—G这个套路如今已经成了欧美乐坛最常见的和弦进行套路

*** Am—C—G—Am（青春）或者Am—F—G—Am《再见青春》。

*** 流行歌曲的和弦进行除了C—Am—F—G这个大套路，还有C—G—Am—Em—F—Em—Dm—G这个套路

*** 麻雀 43564156

*** 我是一只鱼 1345

*** 最美的期待（高潮部分） 1564

*** 阿珍爱上了阿强 636 636 456 456

*** 无论你多怪异我还是会喜欢你吉他谱-《刺客五六七》片尾曲 啦部分1253125 鸡部分5237125

*** 曾经的你  25267675

** 小调

   1、Am—F—C—G（参考曲目：黄义达—我懂、set me free）
   2、Am—C—G—Am（参考曲目：Beyond—灰色轨迹 主歌）
   3、Am—F—G—Am（参考曲目：汪峰—再见青春）
   4、Am—G—F—Am（参考曲目：我的原创—万马奔腾）
   5、Am—F—Am—G（参考曲目：我的原创—未知旅途的风景 主歌）
   6、Am—C—F—C（参考曲目：the cranberries—diying in the sun 主歌）
   Am—G—F—G（参考曲目：扭曲的机器—三十 主歌）
   Am—G—C—Am（参考曲目：较少，暂时没想到）
